services:

  db:
    profiles:
      - dev
    image: postgres:14.5
    container_name: dummy_db
    restart: always
    environment:
      POSTGRES_DB: dummy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dummy-db-volume:/var/lib/postgresql/data
    networks:
      - dummy-network
  
  adminer:
    profiles:
      - adminer
    image: adminer
    restart: always
    ports:
      - 8000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_SYSTEM=pgsql
      - ADMINER_DESIGN=lucas-sandery
    networks:
      - dummy-network

networks:
  dummy-network:
    name: dummy-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  dummy-db-volume:
